# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('num_of_sets', models.PositiveSmallIntegerField(default=2)),
                ('points_per_set', models.PositiveSmallIntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='LeagueRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='league.League')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_played', models.PositiveSmallIntegerField(default=0)),
                ('matches_won', models.PositiveSmallIntegerField(default=0)),
                ('matches_lost', models.PositiveSmallIntegerField(default=0)),
                ('sets_won', models.PositiveSmallIntegerField(default=0)),
                ('sets_lost', models.PositiveSmallIntegerField(default=0)),
                ('set_difference', models.IntegerField(default=0)),
                ('points_won', models.PositiveSmallIntegerField(default=0)),
                ('points_lost', models.PositiveSmallIntegerField(default=0)),
                ('point_difference', models.IntegerField(default=0)),
                ('home_matches_played', models.PositiveSmallIntegerField(default=0)),
                ('home_matches_won', models.PositiveSmallIntegerField(default=0)),
                ('home_matches_lost', models.PositiveSmallIntegerField(default=0)),
                ('away_matches_played', models.PositiveSmallIntegerField(default=0)),
                ('away_matches_won', models.PositiveSmallIntegerField(default=0)),
                ('away_matches_lost', models.PositiveSmallIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='league.League')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='league.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_player_score', models.PositiveSmallIntegerField()),
                ('away_player_score', models.PositiveSmallIntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='league.Match')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_sets', to='league.Player')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='league_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.LeagueRound'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_matches', to='league.Player'),
        ),
        migrations.AddField(
            model_name='league',
            name='players',
            field=models.ManyToManyField(related_name='leagues', to='league.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='ranking',
            unique_together=set([('league', 'player')]),
        ),
    ]
