# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='num_of_sets',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='league',
            name='points_per_set',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
