# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
