# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20160519_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='number',
        ),
    ]
