# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_remove_set_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='finished',
        ),
    ]
